/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;


import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kaan
 */

public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    
    Client c;
    String username;
    public static DefaultListModel lst_messageModel = new DefaultListModel();
    public static DefaultListModel users = new DefaultListModel();
    public static DefaultListModel lst_clientsModel = new DefaultListModel();
    public static DefaultListModel lst_roomsModel = new DefaultListModel();
    public static ArrayList <String> Rooms = new ArrayList();
    
    public MainScreen(String str) {
        initComponents();
        this.username = str;
        room_content_list.setModel(lst_messageModel);
        usersList.setModel(users);
        user_content_list.setModel(lst_clientsModel);
        room_list.setModel(lst_roomsModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        send_room_txt = new javax.swing.JTextField();
        send_user_txt = new javax.swing.JTextField();
        send_room_btn = new javax.swing.JButton();
        send_user_btn = new javax.swing.JButton();
        newRoom_txt = new javax.swing.JTextField();
        create_room_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        room_label = new javax.swing.JLabel();
        conn_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        room_content_list = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        user_content_list = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        room_list = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        refresh_btn = new javax.swing.JButton();
        join_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        send_room_btn.setText("Send To Room");
        send_room_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_room_btnActionPerformed(evt);
            }
        });

        send_user_btn.setText("Send To User");
        send_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_user_btnActionPerformed(evt);
            }
        });

        create_room_btn.setText("Create New Room");
        create_room_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_room_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Users");

        room_label.setText("Rooms");

        conn_btn.setBackground(new java.awt.Color(204, 0, 0));
        conn_btn.setText("CONNECT");
        conn_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conn_btnActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(room_content_list);

        jScrollPane4.setViewportView(user_content_list);

        jScrollPane1.setViewportView(usersList);

        jLabel2.setText("Room Chat");

        jScrollPane2.setViewportView(room_list);

        jLabel3.setText("Client Chat");

        refresh_btn.setText("Refresh Rooms");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });

        join_btn.setText("Join Room");
        join_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                join_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(send_room_txt)
                        .addComponent(send_room_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(newRoom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(create_room_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                    .addComponent(room_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(refresh_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(join_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(send_user_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addComponent(jScrollPane4)
                        .addComponent(jScrollPane1)
                        .addComponent(send_user_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addComponent(conn_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newRoom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(create_room_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(conn_btn)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(room_label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(send_room_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(send_user_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(send_user_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(send_room_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(refresh_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(join_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conn_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conn_btnActionPerformed
        // TODO add your handling code here:
        c = new Client(this);
        try {
            c.Start(username);
            lst_messageModel.addElement("(Now talking to Lobby)");
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        conn_btn.setEnabled(false);

    }//GEN-LAST:event_conn_btnActionPerformed

    private void create_room_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_room_btnActionPerformed
        // TODO add your handling code here:
        if(!newRoom_txt.getText().equals("")){
        String roomName = newRoom_txt.getText();
        Message msg = new Message(Message.Message_Type.CreateRoom);
        msg.content = roomName;
        c.Send(msg);
        newRoom_txt.setText("");
        }else{
            JOptionPane.showMessageDialog(this, "Room name cannot be empty");
        }
    }//GEN-LAST:event_create_room_btnActionPerformed

    private void send_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_user_btnActionPerformed
        // TODO add your handling code here:
        if(!usersList.getSelectedValue().equals("")|!send_user_txt.getText().equals("")){
            String text = send_user_txt.getText();
            Message msg = new Message(Message.Message_Type.UserChat, text, c.username,usersList.getSelectedValue());
            c.Send(msg);
        }
    }//GEN-LAST:event_send_user_btnActionPerformed

    private void send_room_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_room_btnActionPerformed
        // TODO add your handling code here:
       String str= send_room_txt.getText();
       Message msg = new Message(Message.Message_Type.RoomChat,str, c.username);
       c.Send(msg);
       send_room_txt.setText("");
    }//GEN-LAST:event_send_room_btnActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
        Message msg = new Message(Message.Message_Type.Refresh);
        c.Send(msg);
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void join_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_join_btnActionPerformed
        // TODO add your handling code here:
        if(!room_list.getSelectedValue().equals("")){
            c.room=room_list.getSelectedValue();
            Message msg = new Message(Message.Message_Type.JoinRoom);
            msg.content = room_list.getSelectedValue();
            c.Send(msg);
            lst_messageModel.removeAllElements();
            lst_messageModel.addElement("(Now Talking To "+c.room+")");
        }else{
            JOptionPane.showMessageDialog(this, "Please Select A Room ");
        }
    }//GEN-LAST:event_join_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conn_btn;
    private javax.swing.JButton create_room_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton join_btn;
    private javax.swing.JTextField newRoom_txt;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JList<String> room_content_list;
    private javax.swing.JLabel room_label;
    private javax.swing.JList<String> room_list;
    private javax.swing.JButton send_room_btn;
    private javax.swing.JTextField send_room_txt;
    private javax.swing.JButton send_user_btn;
    private javax.swing.JTextField send_user_txt;
    private javax.swing.JList<String> user_content_list;
    private javax.swing.JList<String> usersList;
    // End of variables declaration//GEN-END:variables
}
